import express from 'express';
import cookieParser from 'cookie-parser';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import QRCode from 'qrcode';
import crypto from 'node:crypto';
import pg from 'pg';

const pool=new pg.Pool({connectionString:process.env.DATABASE_URL,ssl:{rejectUnauthorized:false},max:4,connectionTimeoutMillis:10000});
const secret=process.env.JWT_SECRET;
const app=express();app.use(express.json({limit:'100kb'}));app.use(cookieParser());
const query=async(sql,...params)=>(await pool.query(sql,params)).rows;
const one=async(sql,...params)=>(await query(sql,...params))[0];
const fail=(r,c,m)=>r.status(c).json({error:m});
const wrap=fn=>(req,res,next)=>Promise.resolve(fn(req,res,next)).catch(e=>{console.error('API error',e.code||e.message);if(e.code==='23505'||e.code==='23503'||e.code==='23514')return fail(res,400,'Duplicate or invalid value');return fail(res,500,'Request failed');});
const guard=wrap(async(req,res,next)=>{if(!secret||secret.length<32)return fail(res,503,'Authentication not configured');let payload;try{payload=jwt.verify(req.cookies.rs_token,secret)}catch{return fail(res,401,'Please sign in')};const u=await one('SELECT id,username,role,balance_cents FROM users WHERE id=$1',payload.id);if(!u)return fail(res,401,'Please sign in');req.user=u;next()});
const roles=(...allowed)=>(req,res,next)=>allowed.includes(req.user.role)?next():fail(res,403,'Not permitted');
const cost=p=>({...p,price:Number(p.price_cents)/100});
const numeric=v=>Number.isSafeInteger(Number(v))&&Number(v)>0&&Number(v)<=100000000?Number(v):null;
const authCookie=(res,id)=>res.cookie('rs_token',jwt.sign({id},secret,{expiresIn:'7d'}),{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',maxAge:604800000});
app.get('/api/health',wrap(async(_req,res)=>{await query('SELECT 1');res.json({ok:true,database:'connected'})}));
app.post('/api/auth/register',wrap(async(req,res)=>{const {username,password}=req.body||{};if(!/^[a-zA-Z0-9_]{3,30}$/.test(username||'')||typeof password!=='string'||password.length<10||password.length>128)return fail(res,400,'Use 3–30 character username and 10+ character password');if(!secret||secret.length<32)return fail(res,503,'Authentication not configured');const hash=await bcrypt.hash(password,12);const u=await one("INSERT INTO users(username,password_hash,role) VALUES($1,$2,'user') RETURNING id",username,hash);authCookie(res,u.id);res.json({ok:true})}));
app.post('/api/auth/login',wrap(async(req,res)=>{const u=await one('SELECT * FROM users WHERE username=$1',req.body?.username||'');if(!u||!await bcrypt.compare(String(req.body?.password||''),u.password_hash))return fail(res,401,'Invalid credentials');authCookie(res,u.id);res.json({ok:true})}));
app.post('/api/auth/logout',(_req,res)=>{res.clearCookie('rs_token');res.json({ok:true})});
app.get('/api/me',guard,(req,res)=>res.json(req.user));
app.get('/api/categories',wrap(async(_req,res)=>res.json(await query('SELECT * FROM categories ORDER BY id'))));
app.get('/api/products',wrap(async(req,res)=>{const {category,q}=req.query;const rows=await query(`SELECT p.*,c.name category,u.username seller FROM products p LEFT JOIN categories c ON c.id=p.category_id LEFT JOIN users u ON u.id=p.seller_id WHERE p.active=true AND ($1::text IS NULL OR c.slug=$1) AND ($2::text IS NULL OR p.title ILIKE '%'||$2||'%' OR p.description ILIKE '%'||$2||'%') ORDER BY p.id DESC`,category&&category!=='all'?category:null,q||null);res.json(rows.map(cost))}));
app.get('/api/products/:id',wrap(async(req,res)=>{const p=await one('SELECT * FROM products WHERE id=$1 AND active=true',req.params.id);return p?res.json(cost(p)):fail(res,404,'Product not found')}));
app.get('/api/payments',guard,wrap(async(_req,res)=>res.json(await query("SELECT id,code,name,network FROM payment_methods WHERE enabled=true AND address<>''"))));
app.post('/api/deposits',guard,wrap(async(req,res)=>{const amount=numeric(req.body?.amount_cents);if(!amount)return fail(res,400,'Invalid amount');const m=await one("SELECT * FROM payment_methods WHERE id=$1 AND enabled=true AND address<>''",req.body?.method_id);if(!m)return fail(res,400,'Payment method unavailable');const d=await one("INSERT INTO deposits(user_id,method_id,amount_cents,address_snapshot,expires_at) VALUES($1,$2,$3,$4,now()+interval '30 minutes') RETURNING *",req.user.id,m.id,amount,m.address);res.json({id:d.id,amount_cents:amount,address:m.address,code:m.code,network:m.network,expires_at:d.expires_at})}));
app.get('/api/deposits',guard,wrap(async(req,res)=>res.json(await query('SELECT d.*,m.code,m.network FROM deposits d JOIN payment_methods m ON m.id=d.method_id WHERE d.user_id=$1 ORDER BY d.id DESC',req.user.id))));
app.patch('/api/deposits/:id/submit',guard,wrap(async(req,res)=>{const d=await one("UPDATE deposits SET status='pending',txid=$1 WHERE id=$2 AND user_id=$3 AND status='awaiting_payment' AND expires_at>now() RETURNING id",String(req.body?.txid||'').slice(0,200),req.params.id,req.user.id);return d?res.json({ok:true}):fail(res,400,'Deposit already submitted or payment window expired')}));
app.get('/api/wallet',guard,wrap(async(req,res)=>res.json({balance_cents:req.user.balance_cents,ledger:await query('SELECT * FROM ledger WHERE user_id=$1 ORDER BY id DESC',req.user.id)})));
app.post('/api/orders',guard,wrap(async(req,res)=>{const items=req.body?.items;if(!Array.isArray(items)||items.length<1||items.length>40)return fail(res,400,'Invalid cart');const quantities=new Map();for(const it of items){const id=Number(it.id),qty=Number(it.quantity);if(!Number.isSafeInteger(id)||!Number.isSafeInteger(qty)||qty<1||qty>100)return fail(res,400,'Invalid cart');quantities.set(id,(quantities.get(id)||0)+qty)}const client=await pool.connect();try{await client.query('BEGIN');const ordered=[];let total=0;for(const [id,qty] of [...quantities].sort((a,b)=>a[0]-b[0])){const p=(await client.query('SELECT * FROM products WHERE id=$1 AND active=true FOR UPDATE',[id])).rows[0];if(!p||p.stock<qty)throw Error('One or more products are out of stock');total+=Number(p.price_cents)*qty;ordered.push({p,qty})}if(total<=0)throw Error('Invalid order');const debit=await client.query('UPDATE users SET balance_cents=balance_cents-$1 WHERE id=$2 AND balance_cents >= $1 RETURNING id',[total,req.user.id]);if(!debit.rowCount)throw Error('Insufficient wallet balance');const order=(await client.query('INSERT INTO orders(user_id,total_cents) VALUES($1,$2) RETURNING id',[req.user.id,total])).rows[0];for(const {p,qty} of ordered){await client.query('UPDATE products SET stock=stock-$1 WHERE id=$2',[qty,p.id]);await client.query('INSERT INTO order_items(order_id,product_id,seller_id,title,price_cents,quantity,delivery_text) VALUES($1,$2,$3,$4,$5,$6,$7)',[order.id,p.id,p.seller_id,p.title,p.price_cents,qty,p.delivery_text])}await client.query("INSERT INTO ledger(user_id,delta_cents,kind,reference_id) VALUES($1,$2,'purchase',$3)",[req.user.id,-total,order.id]);await client.query('COMMIT');res.json({ok:true,order_id:order.id})}catch(e){await client.query('ROLLBACK');return fail(res,400,e.message)}finally{client.release()}}));
app.get('/api/orders',guard,wrap(async(req,res)=>{const orders=await query('SELECT * FROM orders WHERE user_id=$1 ORDER BY id DESC',req.user.id);for(const o of orders)o.items=await query('SELECT * FROM order_items WHERE order_id=$1',o.id);res.json(orders)}));
app.get('/api/admin/overview',guard,roles('admin'),wrap(async(_req,res)=>{const n=await one("SELECT (SELECT count(*) FROM users)::int users,(SELECT count(*) FROM products)::int products,(SELECT count(*) FROM deposits WHERE status='pending')::int pending,(SELECT count(*) FROM orders)::int orders");res.json(n)}));
app.get('/api/admin/users',guard,roles('admin'),wrap(async(_req,res)=>res.json(await query('SELECT id,username,role,balance_cents,created_at FROM users ORDER BY id DESC'))));
app.patch('/api/admin/users/:id',guard,roles('admin'),wrap(async(req,res)=>{if(!['user','seller','admin'].includes(req.body?.role)||Number(req.params.id)===Number(req.user.id))return fail(res,400,'Invalid role change');const r=await query('UPDATE users SET role=$1 WHERE id=$2 RETURNING id',req.body.role,req.params.id);res.json({ok:!!r.length})}));
app.get('/api/admin/deposits',guard,roles('admin'),wrap(async(_req,res)=>res.json(await query("SELECT d.*,u.username,m.code,m.network FROM deposits d JOIN users u ON u.id=d.user_id JOIN payment_methods m ON m.id=d.method_id ORDER BY CASE WHEN d.status='pending' THEN 0 ELSE 1 END,d.id DESC"))));
app.patch('/api/admin/deposits/:id',guard,roles('admin'),wrap(async(req,res)=>{const status=req.body?.status;if(!['approved','rejected'].includes(status))return fail(res,400,'Invalid status');const client=await pool.connect();try{await client.query('BEGIN');const d=(await client.query("UPDATE deposits SET status=$1,processed_at=now(),processed_by=$2 WHERE id=$3 AND status='pending' RETURNING *",[status,req.user.id,req.params.id])).rows[0];if(!d){await client.query('ROLLBACK');return fail(res,409,'Deposit already processed or missing')}if(status==='approved'){await client.query('UPDATE users SET balance_cents=balance_cents+$1 WHERE id=$2',[d.amount_cents,d.user_id]);await client.query("INSERT INTO ledger(user_id,delta_cents,kind,reference_id) VALUES($1,$2,'deposit',$3)",[d.user_id,d.amount_cents,d.id])}await client.query('COMMIT');res.json({ok:true})}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}}));
app.get('/api/admin/payments',guard,roles('admin'),wrap(async(_req,res)=>res.json(await query('SELECT * FROM payment_methods ORDER BY id'))));
app.patch('/api/admin/payments/:id',guard,roles('admin'),wrap(async(req,res)=>{const address=String(req.body?.address||'').trim();if(address.length>250)return fail(res,400,'Address too long');const r=await query('UPDATE payment_methods SET address=$1,enabled=$2 WHERE id=$3 RETURNING id',address,!!req.body.enabled,req.params.id);res.json({ok:!!r.length})}));
app.post('/api/admin/categories',guard,roles('admin'),wrap(async(req,res)=>{const name=String(req.body?.name||'').trim();if(name.length<2||name.length>60)return fail(res,400,'Invalid category');const slug=name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||crypto.randomUUID().slice(0,8);const r=await one('INSERT INTO categories(name,slug) VALUES($1,$2) RETURNING id',name,slug);res.json(r)}));
app.patch('/api/admin/categories/:id',guard,roles('admin'),wrap(async(req,res)=>{const name=String(req.body?.name||'').trim();if(name.length<2||name.length>60)return fail(res,400,'Invalid category');await query('UPDATE categories SET name=$1 WHERE id=$2',name,req.params.id);res.json({ok:true})}));
app.delete('/api/admin/categories/:id',guard,roles('admin'),wrap(async(req,res)=>{const client=await pool.connect();try{await client.query('BEGIN');await client.query('UPDATE products SET category_id=NULL WHERE category_id=$1',[req.params.id]);await client.query('DELETE FROM categories WHERE id=$1',[req.params.id]);await client.query('COMMIT');res.json({ok:true})}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}}));
app.get('/api/manage/products',guard,roles('admin','seller'),wrap(async(req,res)=>res.json((await query('SELECT p.*,c.name category FROM products p LEFT JOIN categories c ON c.id=p.category_id WHERE ($1::boolean OR p.seller_id=$2) ORDER BY p.id DESC',req.user.role==='admin',req.user.id)).map(cost))));
const productFields=b=>{const title=String(b.title||'').trim(),description=String(b.description||'').trim(),delivery=String(b.delivery_text||'').trim(),image=String(b.image_url||'').trim(),price=Number(b.price),stock=Number(b.stock),category=Number(b.category_id)||null;if(title.length<2||title.length>150||description.length>4000||delivery.length>5000||image.length>500||!Number.isFinite(price)||price<0||price>1000000||!Number.isInteger(stock)||stock<0||stock>10000000||(image&&!/^(https:\/\/|\/assets\/)/.test(image)))throw Error('Invalid product fields');return [category,title,description,Math.round(price*100),stock,image,delivery,b.active!==false]};
app.post('/api/manage/products',guard,roles('admin','seller'),wrap(async(req,res)=>{let a;try{a=productFields(req.body)}catch(e){return fail(res,400,e.message)}const p=await one('INSERT INTO products(category_id,title,description,price_cents,stock,image_url,delivery_text,active,seller_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id',...a,req.user.id);res.json(p)}));
app.patch('/api/manage/products/:id',guard,roles('admin','seller'),wrap(async(req,res)=>{let a;try{a=productFields(req.body)}catch(e){return fail(res,400,e.message)}const p=await one('UPDATE products SET category_id=$1,title=$2,description=$3,price_cents=$4,stock=$5,image_url=$6,delivery_text=$7,active=$8 WHERE id=$9 AND ($10::boolean OR seller_id=$11) RETURNING id',...a,req.params.id,req.user.role==='admin',req.user.id);return p?res.json({ok:true}):fail(res,404,'Product missing or not yours')}));
app.delete('/api/manage/products/:id',guard,roles('admin','seller'),wrap(async(req,res)=>{const p=await one('UPDATE products SET active=false WHERE id=$1 AND ($2::boolean OR seller_id=$3) RETURNING id',req.params.id,req.user.role==='admin',req.user.id);return p?res.json({ok:true}):fail(res,404,'Product missing or not yours')}));
app.get('/api/seller/orders',guard,roles('admin','seller'),wrap(async(req,res)=>res.json(await query('SELECT oi.*,o.created_at,u.username buyer,o.id order_id FROM order_items oi JOIN orders o ON o.id=oi.order_id JOIN users u ON u.id=o.user_id WHERE ($1::boolean OR oi.seller_id=$2) ORDER BY oi.id DESC',req.user.role==='admin',req.user.id))));
app.get('/api/qr',guard,wrap(async(req,res)=>{const d=await one('SELECT address_snapshot FROM deposits WHERE id=$1 AND user_id=$2',req.query.deposit_id,req.user.id);if(!d)return fail(res,404,'Not found');res.type('png').send(await QRCode.toBuffer(d.address_snapshot,{width:260,margin:2}))}));

app.get('/api/seller/application',guard,wrap(async(req,res)=>res.json(await one('SELECT id,full_name,address,service_category,service_demo,status,created_at FROM seller_applications WHERE user_id=$1 ORDER BY id DESC LIMIT 1',req.user.id)||null)));
app.post('/api/seller/application',guard,wrap(async(req,res)=>{
  if(req.user.role!=='user')return fail(res,403,'Only customer accounts may apply');
  const {full_name,address,service_category,service_demo}=req.body||{};
  if([full_name,address,service_category,service_demo].some(v=>typeof v!=='string'||v.trim().length<3||v.length>2000))return fail(res,400,'Complete all seller details and include a demo link or description');
  const last=await one('SELECT status FROM seller_applications WHERE user_id=$1 ORDER BY id DESC LIMIT 1',req.user.id);
  if(last?.status==='pending')return fail(res,409,'Your application is already under review');
  const result=await one('INSERT INTO seller_applications(user_id,full_name,address,service_category,service_demo) VALUES($1,$2,$3,$4,$5) RETURNING id,status',req.user.id,full_name.trim(),address.trim(),service_category.trim(),service_demo.trim());
  res.json(result);
}));
app.get('/api/admin/seller-applications',guard,roles('admin'),wrap(async(req,res)=>res.json(await query('SELECT s.id,s.user_id,u.username,s.full_name,s.address,s.service_category,s.service_demo,s.status,s.created_at FROM seller_applications s JOIN users u ON u.id=s.user_id ORDER BY s.created_at DESC'))));
app.patch('/api/admin/seller-applications/:id',guard,roles('admin'),wrap(async(req,res)=>{
  const status=req.body?.status;
  if(!['approved','rejected'].includes(status))return fail(res,400,'Invalid review action');
  const client=await pool.connect();
  try{
    await client.query('BEGIN');
    const found=await client.query("SELECT id,user_id FROM seller_applications WHERE id=$1 AND status='pending' FOR UPDATE",[req.params.id]);
    if(!found.rowCount){await client.query('ROLLBACK');return fail(res,409,'Application has already been reviewed')}
    const u=await client.query('SELECT role FROM users WHERE id=$1 FOR UPDATE',[found.rows[0].user_id]);
    if(u.rows[0]?.role!=='user'){await client.query('ROLLBACK');return fail(res,409,'Applicant role has changed')}
    if(status==='approved')await client.query("UPDATE users SET role='seller' WHERE id=$1",[found.rows[0].user_id]);
    await client.query('UPDATE seller_applications SET status=$1,reviewed_at=now(),reviewed_by=$2 WHERE id=$3',[status,req.user.id,req.params.id]);
    await client.query('COMMIT');res.json({ok:true,status});
  }catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}
}));
export default app;
