import express from 'express';
import cookieParser from 'cookie-parser';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import Database from 'better-sqlite3';
import QRCode from 'qrcode';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import crypto from 'node:crypto';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
for (const l of (fs.existsSync(path.join(root,'.env')) ? fs.readFileSync(path.join(root,'.env'),'utf8').split(/\r?\n/) : [])) { const i=l.indexOf('=');if(i>0 && !l.startsWith('#')) process.env[l.slice(0,i).trim()] ??= l.slice(i+1).trim(); }
const SECRET=process.env.JWT_SECRET;
if(!SECRET || SECRET.length<32 || SECRET.includes('REPLACE_WITH')) throw new Error('Set secure JWT_SECRET of at least 32 characters in .env');
const dbPath=path.resolve(root,process.env.DATABASE_PATH||'./data/russian-shadow.sqlite');fs.mkdirSync(path.dirname(dbPath),{recursive:true});
const db=new Database(dbPath);db.pragma('journal_mode = WAL');db.pragma('foreign_keys = ON');
db.exec(`
CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY,username TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'user' CHECK(role IN ('user','seller','admin')),balance_cents INTEGER NOT NULL DEFAULT 0 CHECK(balance_cents>=0),created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS categories(id INTEGER PRIMARY KEY,name TEXT UNIQUE NOT NULL,slug TEXT UNIQUE NOT NULL);
CREATE TABLE IF NOT EXISTS products(id INTEGER PRIMARY KEY,seller_id INTEGER REFERENCES users(id),category_id INTEGER REFERENCES categories(id),title TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',price_cents INTEGER NOT NULL CHECK(price_cents>=0),stock INTEGER NOT NULL DEFAULT 0 CHECK(stock>=0),image_url TEXT NOT NULL DEFAULT '',delivery_text TEXT NOT NULL DEFAULT '',active INTEGER NOT NULL DEFAULT 1,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS payment_methods(id INTEGER PRIMARY KEY,code TEXT UNIQUE,name TEXT NOT NULL,address TEXT NOT NULL DEFAULT '',network TEXT NOT NULL,enabled INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS deposits(id INTEGER PRIMARY KEY,user_id INTEGER NOT NULL REFERENCES users(id),method_id INTEGER NOT NULL REFERENCES payment_methods(id),amount_cents INTEGER NOT NULL CHECK(amount_cents>0),address_snapshot TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'awaiting_payment' CHECK(status IN ('awaiting_payment','pending','approved','rejected')),txid TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,expires_at TEXT NOT NULL,processed_at TEXT,processed_by INTEGER REFERENCES users(id));
CREATE TABLE IF NOT EXISTS orders(id INTEGER PRIMARY KEY,user_id INTEGER NOT NULL REFERENCES users(id),total_cents INTEGER NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS order_items(id INTEGER PRIMARY KEY,order_id INTEGER NOT NULL REFERENCES orders(id),product_id INTEGER REFERENCES products(id),seller_id INTEGER REFERENCES users(id),title TEXT NOT NULL,price_cents INTEGER NOT NULL,quantity INTEGER NOT NULL,delivery_text TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS ledger(id INTEGER PRIMARY KEY,user_id INTEGER NOT NULL REFERENCES users(id),delta_cents INTEGER NOT NULL,kind TEXT NOT NULL,reference_id INTEGER NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP,UNIQUE(user_id,kind,reference_id));
`);
const addUser=(name,pass,role)=>{if(name&&pass&&!db.prepare('SELECT id FROM users WHERE username=?').get(name)) db.prepare('INSERT INTO users(username,password_hash,role) VALUES(?,?,?)').run(name,bcrypt.hashSync(pass,12),role);};
addUser(process.env.ADMIN_USERNAME,process.env.ADMIN_PASSWORD,'admin');addUser(process.env.SELLER_USERNAME,process.env.SELLER_PASSWORD,'seller');
for(const name of ['Digital Products','Electronics','Accessories','Courses & eBooks','Premium Services','Security Tools'])db.prepare('INSERT OR IGNORE INTO categories(name,slug) VALUES(?,?)').run(name,name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/-$/,''));
for(const [code,name,network] of [['BTC','Bitcoin','Bitcoin'],['TRC20','USDT TRC20','TRON'],['ETH','Ethereum','Ethereum'],['ERC20','USDT ERC20','Ethereum']])db.prepare('INSERT OR IGNORE INTO payment_methods(code,name,network) VALUES(?,?,?)').run(code,name,network);
if(!db.prepare('SELECT id FROM products LIMIT 1').get()){
 const seller=db.prepare("SELECT id FROM users WHERE role IN ('seller','admin') ORDER BY CASE role WHEN 'seller' THEN 0 ELSE 1 END LIMIT 1").get();
 if(seller){const items=[['Portable WiFi Router','Travel-friendly wireless router with multi-device support.',99,24,2],['Premium VPN Setup Guide','Digital setup guide for private browsing best practices.',5,999,1],['4K Compact Camera','Compact high-definition indoor/outdoor camera.',45,18,2],['Social Media Creator Pack','Editable templates and design resources for creators.',15,200,1],['Cybersecurity Essentials Course','Self-paced introductory defensive cybersecurity course.',25,300,4],['Mini Camera Drone','Compact drone for aerial photography.',120,9,2]];items.forEach(([title,description,price,stock,cat],i)=>db.prepare('INSERT INTO products(seller_id,category_id,title,description,price_cents,stock,image_url,delivery_text) VALUES(?,?,?,?,?,?,?,?)').run(seller.id,cat,title,description,price*100,stock,`/assets/item-${i+1}.png`,`Thank you for purchasing ${title}. Contact the seller through your order number for fulfilment.`));}
}
const app=express();app.use(helmet({contentSecurityPolicy:false}));app.use(express.json({limit:'100kb'}));app.use(cookieParser());
app.use('/api/auth',rateLimit({windowMs:15*60*1000,limit:35,standardHeaders:'draft-7',legacyHeaders:false}));
const fail=(res,code,msg)=>res.status(code).json({error:msg});
const safe=(f)=>(req,res)=>{try{return f(req,res);}catch(err){if(err.code?.startsWith('SQLITE_CONSTRAINT')) return fail(res,400,'Invalid or duplicate value'); console.error(err);return fail(res,500,'Request failed');}};
const auth=(req,res,next)=>{try{const t=req.cookies.rs_token;const p=jwt.verify(t,SECRET);const user=db.prepare('SELECT id,username,role,balance_cents FROM users WHERE id=?').get(p.id);if(!user)return fail(res,401,'Please sign in');req.user=user;next();}catch{return fail(res,401,'Please sign in');}};
const role=(...roles)=>(req,res,next)=>roles.includes(req.user.role)?next():fail(res,403,'Not permitted');
const money=v=>Number.isInteger(Number(v))&&Number(v)>0&&Number(v)<=100000000?Number(v):null;
const productOut=p=>({...p,price:p.price_cents/100});
app.post('/api/auth/register',safe((req,res)=>{const {username,password}=req.body;if(!/^[a-zA-Z0-9_]{3,30}$/.test(username||'')||typeof password!=='string'||password.length<10||password.length>128)return fail(res,400,'Use a 3–30 character username and password of 10+ characters');const hash=bcrypt.hashSync(password,12);const result=db.prepare("INSERT INTO users(username,password_hash,role) VALUES(?,?,'user')").run(username,hash);const token=jwt.sign({id:result.lastInsertRowid},SECRET,{expiresIn:'7d'});res.cookie('rs_token',token,{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:604800000});res.json({ok:true});}));
app.post('/api/auth/login',safe((req,res)=>{const {username,password}=req.body;const u=db.prepare('SELECT * FROM users WHERE username=?').get(username);if(!u||!bcrypt.compareSync(String(password||''),u.password_hash))return fail(res,401,'Invalid credentials');const token=jwt.sign({id:u.id},SECRET,{expiresIn:'7d'});res.cookie('rs_token',token,{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:604800000});res.json({ok:true});}));
app.post('/api/auth/logout',(_req,res)=>{res.clearCookie('rs_token');res.json({ok:true});});
app.get('/api/me',auth,(req,res)=>res.json(req.user));
app.get('/api/categories',safe((_req,res)=>res.json(db.prepare('SELECT * FROM categories ORDER BY id').all())));
app.get('/api/products',safe((req,res)=>{const {category,q}=req.query;let query='SELECT p.*,c.name AS category,u.username AS seller FROM products p LEFT JOIN categories c ON p.category_id=c.id LEFT JOIN users u ON p.seller_id=u.id WHERE p.active=1';const params=[];if(category&&category!=='all'){query+=' AND c.slug=?';params.push(category);}if(q){query+=' AND (p.title LIKE ? OR p.description LIKE ?)';params.push(`%${q}%`,`%${q}%`);}query+=' ORDER BY p.id DESC';res.json(db.prepare(query).all(...params).map(productOut));}));
app.get('/api/products/:id',safe((req,res)=>{const p=db.prepare('SELECT * FROM products WHERE id=? AND active=1').get(req.params.id);return p?res.json(productOut(p)):fail(res,404,'Product not found');}));
app.get('/api/payments',auth,safe((_req,res)=>res.json(db.prepare("SELECT id,code,name,network FROM payment_methods WHERE enabled=1 AND address<>''").all())));
app.post('/api/deposits',auth,safe((req,res)=>{const cents=money(req.body.amount_cents);if(!cents)return fail(res,400,'Invalid amount');const m=db.prepare("SELECT * FROM payment_methods WHERE id=? AND enabled=1 AND address<>''").get(req.body.method_id);if(!m)return fail(res,400,'Payment method unavailable');const expires=new Date(Date.now()+1800000).toISOString();const r=db.prepare('INSERT INTO deposits(user_id,method_id,amount_cents,address_snapshot,expires_at) VALUES(?,?,?,?,?)').run(req.user.id,m.id,cents,m.address,expires);res.json({id:r.lastInsertRowid,amount_cents:cents,address:m.address,code:m.code,network:m.network,expires_at:expires});}));
app.get('/api/deposits',auth,safe((req,res)=>res.json(db.prepare('SELECT d.*,m.code,m.network FROM deposits d JOIN payment_methods m ON m.id=d.method_id WHERE d.user_id=? ORDER BY d.id DESC').all(req.user.id))));
app.patch('/api/deposits/:id/submit',auth,safe((req,res)=>{const txid=String(req.body.txid||'').trim().slice(0,200);const d=db.prepare('SELECT * FROM deposits WHERE id=? AND user_id=?').get(req.params.id,req.user.id);if(!d)return fail(res,404,'Deposit not found');if(d.status!=='awaiting_payment')return fail(res,400,'Deposit already submitted or reviewed');if(Date.parse(d.expires_at)<Date.now())return fail(res,400,'This payment window expired. Create a new request.');db.prepare("UPDATE deposits SET txid=?,status='pending' WHERE id=?").run(txid,d.id);res.json({ok:true});}));
app.get('/api/wallet',auth,safe((req,res)=>res.json({balance_cents:req.user.balance_cents,ledger:db.prepare('SELECT * FROM ledger WHERE user_id=? ORDER BY id DESC').all(req.user.id)})));
app.post('/api/orders',auth,safe((req,res)=>{const items=req.body.items;if(!Array.isArray(items)||!items.length||items.length>40)return fail(res,400,'Cart is empty or too large');const compact=new Map();for(const item of items){const id=Number(item.id),qty=Number(item.quantity);if(!Number.isInteger(id)||!Number.isInteger(qty)||qty<1||qty>100)return fail(res,400,'Invalid cart');compact.set(id,(compact.get(id)||0)+qty);}const rows=[];let total=0;for(const [id,qty] of compact){const p=db.prepare('SELECT * FROM products WHERE id=? AND active=1').get(id);if(!p||p.stock<qty)return fail(res,400,'One or more products are out of stock');total+=p.price_cents*qty;rows.push({p,qty});}if(total<=0)return fail(res,400,'Invalid order');const checkout=db.transaction(()=>{const debit=db.prepare('UPDATE users SET balance_cents=balance_cents-? WHERE id=? AND balance_cents>=?').run(total,req.user.id,total);if(!debit.changes)throw new Error('INSUFFICIENT_BALANCE');for(const {p,qty} of rows){const upd=db.prepare('UPDATE products SET stock=stock-? WHERE id=? AND stock>=?').run(qty,p.id,qty);if(!upd.changes)throw new Error('OUT_OF_STOCK');}const r=db.prepare('INSERT INTO orders(user_id,total_cents) VALUES(?,?)').run(req.user.id,total);for(const {p,qty} of rows)db.prepare('INSERT INTO order_items(order_id,product_id,seller_id,title,price_cents,quantity,delivery_text) VALUES(?,?,?,?,?,?,?)').run(r.lastInsertRowid,p.id,p.seller_id,p.title,p.price_cents,qty,p.delivery_text);db.prepare("INSERT INTO ledger(user_id,delta_cents,kind,reference_id) VALUES(?,?,'purchase',?)").run(req.user.id,-total,r.lastInsertRowid);return r.lastInsertRowid;});try{res.json({ok:true,order_id:checkout()});}catch(e){return fail(res,400,e.message==='INSUFFICIENT_BALANCE'?'Insufficient wallet balance':'Inventory changed. Try again');}}));
app.get('/api/orders',auth,safe((req,res)=>{const orders=db.prepare('SELECT * FROM orders WHERE user_id=? ORDER BY id DESC').all(req.user.id);for(const o of orders)o.items=db.prepare('SELECT * FROM order_items WHERE order_id=?').all(o.id);res.json(orders);}));
app.get('/api/admin/overview',auth,role('admin'),safe((_req,res)=>res.json({users:db.prepare('SELECT COUNT(*) n FROM users').get().n,products:db.prepare('SELECT COUNT(*) n FROM products').get().n,pending:db.prepare("SELECT COUNT(*) n FROM deposits WHERE status='pending'").get().n,orders:db.prepare('SELECT COUNT(*) n FROM orders').get().n})));
app.get('/api/admin/users',auth,role('admin'),safe((_req,res)=>res.json(db.prepare('SELECT id,username,role,balance_cents,created_at FROM users ORDER BY id DESC').all())));
app.patch('/api/admin/users/:id',auth,role('admin'),safe((req,res)=>{if(!['user','seller','admin'].includes(req.body.role))return fail(res,400,'Invalid role');if(Number(req.params.id)===req.user.id)return fail(res,400,'Cannot change your own role');const u=db.prepare('UPDATE users SET role=? WHERE id=?').run(req.body.role,req.params.id);res.json({ok:!!u.changes});}));
app.get('/api/admin/deposits',auth,role('admin'),safe((_req,res)=>res.json(db.prepare('SELECT d.*,u.username,m.code,m.network FROM deposits d JOIN users u ON u.id=d.user_id JOIN payment_methods m ON m.id=d.method_id ORDER BY CASE d.status WHEN \'pending\' THEN 0 ELSE 1 END,d.id DESC').all())));
app.patch('/api/admin/deposits/:id',auth,role('admin'),safe((req,res)=>{const status=req.body.status;if(!['approved','rejected'].includes(status))return fail(res,400,'Invalid status');const apply=db.transaction(()=>{const d=db.prepare('SELECT * FROM deposits WHERE id=?').get(req.params.id);if(!d||d.status!=='pending')return false;db.prepare('UPDATE deposits SET status=?,processed_at=CURRENT_TIMESTAMP,processed_by=? WHERE id=?').run(status,req.user.id,d.id);if(status==='approved'){db.prepare('UPDATE users SET balance_cents=balance_cents+? WHERE id=?').run(d.amount_cents,d.user_id);db.prepare("INSERT INTO ledger(user_id,delta_cents,kind,reference_id) VALUES(?,?,'deposit',?)").run(d.user_id,d.amount_cents,d.id);}return true;});if(!apply())return fail(res,409,'Deposit already processed or missing');res.json({ok:true});}));
app.get('/api/admin/payments',auth,role('admin'),safe((_req,res)=>res.json(db.prepare('SELECT * FROM payment_methods ORDER BY id').all())));
app.patch('/api/admin/payments/:id',auth,role('admin'),safe((req,res)=>{const address=String(req.body.address||'').trim();if(address.length>250)return fail(res,400,'Address too long');const enabled=req.body.enabled?1:0;const r=db.prepare('UPDATE payment_methods SET address=?,enabled=? WHERE id=?').run(address,enabled,req.params.id);res.json({ok:!!r.changes});}));
app.post('/api/admin/categories',auth,role('admin'),safe((req,res)=>{const name=String(req.body.name||'').trim();if(name.length<2||name.length>60)return fail(res,400,'Invalid category');const slug=name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||crypto.randomUUID().slice(0,8);const r=db.prepare('INSERT INTO categories(name,slug) VALUES(?,?)').run(name,slug);res.json({id:r.lastInsertRowid});}));
app.patch('/api/admin/categories/:id',auth,role('admin'),safe((req,res)=>{const name=String(req.body.name||'').trim();if(name.length<2||name.length>60)return fail(res,400,'Invalid category');db.prepare('UPDATE categories SET name=? WHERE id=?').run(name,req.params.id);res.json({ok:true});}));
app.delete('/api/admin/categories/:id',auth,role('admin'),safe((req,res)=>{db.prepare('UPDATE products SET category_id=NULL WHERE category_id=?').run(req.params.id);db.prepare('DELETE FROM categories WHERE id=?').run(req.params.id);res.json({ok:true});}));
app.get('/api/manage/products',auth,role('admin','seller'),safe((req,res)=>res.json(db.prepare(`SELECT p.*,c.name category FROM products p LEFT JOIN categories c ON c.id=p.category_id ${req.user.role==='seller'?'WHERE p.seller_id=?':''} ORDER BY p.id DESC`).all(...(req.user.role==='seller'?[req.user.id]:[])).map(productOut))));
const parseProduct=b=>{const title=String(b.title||'').trim(),description=String(b.description||'').trim(),delivery_text=String(b.delivery_text||'').trim(),image_url=String(b.image_url||'').trim(),price=Number(b.price),stock=Number(b.stock),category_id=Number(b.category_id)||null;if(title.length<2||title.length>150||description.length>4000||delivery_text.length>5000||image_url.length>500||!Number.isFinite(price)||price<0||price>1000000||!Number.isInteger(stock)||stock<0||stock>10000000||image_url && !(/^(https:\/\/|\/assets\/)/.test(image_url)))throw new Error('Invalid product fields');return {title,description,delivery_text,image_url,price_cents:Math.round(price*100),stock,category_id,active:b.active===false?0:1};};
app.post('/api/manage/products',auth,role('admin','seller'),safe((req,res)=>{let p;try{p=parseProduct(req.body);}catch(e){return fail(res,400,e.message);}const r=db.prepare('INSERT INTO products(seller_id,category_id,title,description,price_cents,stock,image_url,delivery_text,active) VALUES(@seller_id,@category_id,@title,@description,@price_cents,@stock,@image_url,@delivery_text,@active)').run({...p,seller_id:req.user.id});res.json({id:r.lastInsertRowid});}));
app.patch('/api/manage/products/:id',auth,role('admin','seller'),safe((req,res)=>{const old=db.prepare('SELECT * FROM products WHERE id=?').get(req.params.id);if(!old)return fail(res,404,'Product missing');if(req.user.role!=='admin'&&old.seller_id!==req.user.id)return fail(res,403,'Not your product');let p;try{p=parseProduct(req.body);}catch(e){return fail(res,400,e.message);}db.prepare('UPDATE products SET category_id=@category_id,title=@title,description=@description,price_cents=@price_cents,stock=@stock,image_url=@image_url,delivery_text=@delivery_text,active=@active WHERE id=@id').run({...p,id:old.id});res.json({ok:true});}));
app.delete('/api/manage/products/:id',auth,role('admin','seller'),safe((req,res)=>{const p=db.prepare('SELECT seller_id FROM products WHERE id=?').get(req.params.id);if(!p)return fail(res,404,'Not found');if(req.user.role!=='admin'&&p.seller_id!==req.user.id)return fail(res,403,'Not your product');db.prepare('UPDATE products SET active=0 WHERE id=?').run(req.params.id);res.json({ok:true});}));
app.get('/api/seller/orders',auth,role('admin','seller'),safe((req,res)=>res.json(db.prepare(`SELECT oi.*,o.created_at,u.username buyer,o.id order_id FROM order_items oi JOIN orders o ON o.id=oi.order_id JOIN users u ON u.id=o.user_id ${req.user.role==='seller'?'WHERE oi.seller_id=?':''} ORDER BY oi.id DESC`).all(...(req.user.role==='seller'?[req.user.id]:[])))));
app.get('/api/qr',auth,async(req,res)=>{try{const d=db.prepare('SELECT * FROM deposits WHERE id=? AND user_id=?').get(req.query.deposit_id,req.user.id);if(!d)return fail(res,404,'Not found');const png=await QRCode.toBuffer(d.address_snapshot,{width:260,margin:2});res.type('png').send(png);}catch{return fail(res,500,'QR failed');}});
const dist=path.join(root,'dist');if(fs.existsSync(dist)){app.use(express.static(dist));app.get('*',(req,res)=>res.sendFile(path.join(dist,'index.html')));}
const port=Number(process.env.PORT||4000);app.listen(port,()=>console.log(`Russian Shadow API listening on :${port}`));
